(Module
    [(FunctionDef
        test_List
        ([]
        []
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                a
                Store
            )
            (Subscript
                (Name
                    list
                    Load
                )
                (Name
                    i32
                    Load
                )
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                a
                Store
            )]
            (List
                [(ConstantInt
                    1
                    ()
                )
                (ConstantInt
                    2
                    ()
                )
                (ConstantInt
                    3
                    ()
                )]
                Load
            )
            ()
        )
        (Assign
            [(Name
                a
                Store
            )]
            (List
                [(UnaryOp
                    USub
                    (ConstantInt
                        3
                        ()
                    )
                )
                (UnaryOp
                    USub
                    (ConstantInt
                        2
                        ()
                    )
                )
                (UnaryOp
                    USub
                    (ConstantInt
                        1
                        ()
                    )
                )]
                Load
            )
            ()
        )
        (AnnAssign
            (Name
                b
                Store
            )
            (Subscript
                (Name
                    list
                    Load
                )
                (Name
                    str
                    Load
                )
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                b
                Store
            )]
            (List
                [(ConstantStr
                    "a"
                    ()
                )
                (ConstantStr
                    "b"
                    ()
                )
                (ConstantStr
                    "c"
                    ()
                )]
                Load
            )
            ()
        )
        (AnnAssign
            (Name
                c
                Store
            )
            (Subscript
                (Name
                    list
                    Load
                )
                (Subscript
                    (Name
                        list
                        Load
                    )
                    (Name
                        i32
                        Load
                    )
                    Load
                )
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                c
                Store
            )]
            (List
                [(List
                    [(ConstantInt
                        1
                        ()
                    )
                    (ConstantInt
                        2
                        ()
                    )
                    (ConstantInt
                        3
                        ()
                    )]
                    Load
                )
                (List
                    [(ConstantInt
                        4
                        ()
                    )
                    (ConstantInt
                        5
                        ()
                    )
                    (ConstantInt
                        6
                        ()
                    )]
                    Load
                )]
                Load
            )
            ()
        )
        (AnnAssign
            (Name
                d
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                d
                Store
            )]
            (Subscript
                (Name
                    a
                    Load
                )
                (ConstantInt
                    2
                    ()
                )
                Load
            )
            ()
        )
        (AnnAssign
            (Name
                e
                Store
            )
            (Subscript
                (Name
                    list
                    Load
                )
                (Subscript
                    (Name
                        list
                        Load
                    )
                    (Name
                        str
                        Load
                    )
                    Load
                )
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                e
                Store
            )]
            (List
                [(List
                    [(ConstantStr
                        "a"
                        ()
                    )
                    (ConstantStr
                        "b"
                        ()
                    )
                    (ConstantStr
                        "c"
                        ()
                    )]
                    Load
                )
                (List
                    [(ConstantStr
                        "d"
                        ()
                    )
                    (ConstantStr
                        "e"
                        ()
                    )]
                    Load
                )]
                Load
            )
            ()
        )
        (Expr
            (Call
                (Attribute
                    (Name
                        a
                        Load
                    )
                    append
                    Load
                )
                [(ConstantInt
                    10
                    ()
                )]
                []
            )
        )
        (Expr
            (Call
                (Attribute
                    (Name
                        a
                        Load
                    )
                    remove
                    Load
                )
                [(ConstantInt
                    1
                    ()
                )]
                []
            )
        )
        (Expr
            (Call
                (Attribute
                    (Name
                        a
                        Load
                    )
                    insert
                    Load
                )
                [(ConstantInt
                    2
                    ()
                )
                (ConstantInt
                    13
                    ()
                )]
                []
            )
        )
        (Assign
            [(Name
                a
                Store
            )]
            (Subscript
                (Name
                    a
                    Load
                )
                (Slice
                    (ConstantInt
                        0
                        ()
                    )
                    (ConstantInt
                        2
                        ()
                    )
                    ()
                )
                Load
            )
            ()
        )
        (Assign
            [(Name
                d
                Store
            )]
            (Call
                (Attribute
                    (Name
                        a
                        Load
                    )
                    pop
                    Load
                )
                []
                []
            )
            ()
        )
        (Assign
            [(Name
                d
                Store
            )]
            (Call
                (Attribute
                    (Name
                        a
                        Load
                    )
                    pop
                    Load
                )
                [(ConstantInt
                    2
                    ()
                )]
                []
            )
            ()
        )
        (AugAssign
            (Name
                a
                Store
            )
            Add
            (List
                [(ConstantInt
                    4
                    ()
                )
                (ConstantInt
                    5
                    ()
                )]
                Load
            )
        )
        (Assign
            [(Name
                a
                Store
            )]
            (BinOp
                (List
                    [(ConstantInt
                        6
                        ()
                    )
                    (ConstantInt
                        7
                        ()
                    )]
                    Load
                )
                Add
                (Name
                    a
                    Load
                )
            )
            ()
        )
        (AnnAssign
            (Name
                a11
                Store
            )
            (Subscript
                (Name
                    list
                    Load
                )
                (Name
                    i32
                    Load
                )
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                b11
                Store
            )
            (Subscript
                (Name
                    list
                    Load
                )
                (Name
                    i32
                    Load
                )
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                a11
                Store
            )]
            (List
                [(ConstantInt
                    1
                    ()
                )
                (ConstantInt
                    2
                    ()
                )]
                Load
            )
            ()
        )
        (Assign
            [(Name
                b11
                Store
            )]
            (List
                [(ConstantInt
                    3
                    ()
                )
                (ConstantInt
                    4
                    ()
                )]
                Load
            )
            ()
        )
        (Assert
            (Compare
                (Name
                    a11
                    Load
                )
                Eq
                [(Name
                    b11
                    Load
                )]
            )
            ()
        )]
        []
        ()
        ()
    )]
    []
)
