(Module
    [(FunctionDef
        test_StrOp_concat
        ([]
        []
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                s
                Store
            )
            (Name
                str
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                s
                Store
            )]
            (BinOp
                (ConstantStr
                    "3"
                    ()
                )
                Add
                (ConstantStr
                    "4"
                    ()
                )
            )
            ()
        )
        (Assign
            [(Name
                s
                Store
            )]
            (BinOp
                (ConstantStr
                    "a "
                    ()
                )
                Add
                (ConstantStr
                    "test"
                    ()
                )
            )
            ()
        )
        (Assign
            [(Name
                s
                Store
            )]
            (BinOp
                (BinOp
                    (ConstantStr
                        "test"
                        ()
                    )
                    Add
                    (ConstantStr
                        "test"
                        ()
                    )
                )
                Add
                (ConstantStr
                    "test"
                    ()
                )
            )
            ()
        )]
        []
        ()
        ()
    )]
    []
)
