(Module
    [(FunctionDef
        test_subscript
        ([]
        []
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                s
                Store
            )
            (Name
                str
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                s
                Store
            )]
            (ConstantStr
                "abc"
                ()
            )
            ()
        )
        (Assign
            [(Name
                s
                Store
            )]
            (Subscript
                (Name
                    s
                    Load
                )
                (ConstantInt
                    0
                    ()
                )
                Load
            )
            ()
        )
        (Assign
            [(Name
                s
                Store
            )]
            (Subscript
                (Name
                    s
                    Load
                )
                (Slice
                    (ConstantInt
                        1
                        ()
                    )
                    (ConstantInt
                        2
                        ()
                    )
                    ()
                )
                Load
            )
            ()
        )
        (Assign
            [(Name
                s
                Store
            )]
            (Subscript
                (Name
                    s
                    Load
                )
                (Slice
                    ()
                    ()
                    ()
                )
                Load
            )
            ()
        )
        (Assign
            [(Name
                s
                Store
            )]
            (Subscript
                (Name
                    s
                    Load
                )
                (Slice
                    ()
                    ()
                    (UnaryOp
                        USub
                        (ConstantInt
                            1
                            ()
                        )
                    )
                )
                Load
            )
            ()
        )
        (Assign
            [(Name
                s
                Store
            )]
            (Subscript
                (Name
                    s
                    Load
                )
                (Slice
                    ()
                    ()
                    (ConstantInt
                        2
                        ()
                    )
                )
                Load
            )
            ()
        )
        (Assign
            [(Name
                s
                Store
            )]
            (Subscript
                (Name
                    s
                    Load
                )
                (Slice
                    (ConstantInt
                        1
                        ()
                    )
                    (ConstantInt
                        88
                        ()
                    )
                    (ConstantInt
                        1
                        ()
                    )
                )
                Load
            )
            ()
        )
        (Assign
            [(Name
                s
                Store
            )]
            (Subscript
                (Name
                    s
                    Load
                )
                (Slice
                    ()
                    (ConstantInt
                        1
                        ()
                    )
                    (UnaryOp
                        USub
                        (ConstantInt
                            4
                            ()
                        )
                    )
                )
                Load
            )
            ()
        )
        (Assign
            [(Name
                s
                Store
            )]
            (Subscript
                (Name
                    s
                    Load
                )
                (Slice
                    (UnaryOp
                        USub
                        (ConstantInt
                            89
                            ()
                        )
                    )
                    ()
                    (ConstantInt
                        4
                        ()
                    )
                )
                Load
            )
            ()
        )
        (Assign
            [(Name
                s
                Store
            )]
            (Subscript
                (Name
                    s
                    Load
                )
                (Slice
                    (UnaryOp
                        USub
                        (ConstantInt
                            3
                            ()
                        )
                    )
                    (UnaryOp
                        USub
                        (ConstantInt
                            3
                            ()
                        )
                    )
                    (UnaryOp
                        USub
                        (ConstantInt
                            3
                            ()
                        )
                    )
                )
                Load
            )
            ()
        )
        (Assign
            [(Name
                s
                Store
            )]
            (Subscript
                (Name
                    s
                    Load
                )
                (Slice
                    (ConstantInt
                        2
                        ()
                    )
                    (ConstantInt
                        3
                        ()
                    )
                    ()
                )
                Load
            )
            ()
        )
        (AnnAssign
            (Name
                A
                Store
            )
            (Subscript
                (Name
                    i32
                    Load
                )
                (ConstantInt
                    5
                    ()
                )
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                B
                Store
            )
            (Subscript
                (Name
                    i32
                    Load
                )
                (ConstantInt
                    2
                    ()
                )
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                i
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                i
                Store
            )]
            (Subscript
                (Name
                    A
                    Load
                )
                (ConstantInt
                    0
                    ()
                )
                Load
            )
            ()
        )
        (Assign
            [(Name
                B
                Store
            )]
            (Subscript
                (Name
                    A
                    Load
                )
                (Slice
                    (ConstantInt
                        1
                        ()
                    )
                    (ConstantInt
                        3
                        ()
                    )
                    ()
                )
                Load
            )
            ()
        )
        (Assign
            [(Name
                B
                Store
            )]
            (Subscript
                (Name
                    A
                    Load
                )
                (Slice
                    (ConstantInt
                        1
                        ()
                    )
                    (ConstantInt
                        2
                        ()
                    )
                    (ConstantInt
                        3
                        ()
                    )
                )
                Load
            )
            ()
        )]
        []
        ()
        ()
    )]
    []
)
