(Module
    [(FunctionDef
        test_pass
        ([]
        []
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                a
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                a
                Store
            )]
            (ConstantInt
                1
                ()
            )
            ()
        )
        (While
            (Compare
                (Name
                    a
                    Load
                )
                Gt
                [(ConstantInt
                    0
                    ()
                )]
            )
            [(Pass)]
            []
        )]
        []
        ()
        ()
    )]
    []
)
