(Module
    [(FunctionDef
        test_del
        ([]
        []
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                a
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                b
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                a
                Store
            )]
            (ConstantInt
                4
                ()
            )
            ()
        )
        (Assign
            [(Name
                b
                Store
            )]
            (ConstantInt
                20
                ()
            )
            ()
        )
        (Delete
            [(Name
                a
                Del
            )
            (Name
                b
                Del
            )]
        )]
        []
        ()
        ()
    )]
    []
)
