(Module
    [(ImportFrom
        lpython
        [(i32
        ())]
        0
    )
    (FunctionDef
        test_pow
        ([]
        []
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                a
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                a
                Store
            )]
            (Call
                (Name
                    i32
                    Load
                )
                [(Call
                    (Name
                        pow
                        Load
                    )
                    [(ConstantInt
                        2
                        ()
                    )
                    (ConstantInt
                        2
                        ()
                    )]
                    []
                )]
                []
            )
            ()
        )]
        []
        ()
        ()
    )
    (FunctionDef
        test_pow_1
        ([]
        [(a
        (Name
            i32
            Load
        )
        ())
        (b
        (Name
            i32
            Load
        )
        ())]
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                res
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                res
                Store
            )]
            (Call
                (Name
                    i32
                    Load
                )
                [(Call
                    (Name
                        pow
                        Load
                    )
                    [(Name
                        a
                        Load
                    )
                    (Name
                        b
                        Load
                    )]
                    []
                )]
                []
            )
            ()
        )
        (Return
            (Name
                res
                Load
            )
        )]
        []
        (Name
            i32
            Load
        )
        ()
    )
    (FunctionDef
        main0
        ([]
        []
        []
        []
        []
        []
        [])
        [(Expr
            (Call
                (Name
                    test_pow
                    Load
                )
                []
                []
            )
        )
        (AnnAssign
            (Name
                c
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                c
                Store
            )]
            (Call
                (Name
                    test_pow_1
                    Load
                )
                [(ConstantInt
                    1
                    ()
                )
                (ConstantInt
                    2
                    ()
                )]
                []
            )
            ()
        )]
        []
        ()
        ()
    )
    (Expr
        (Call
            (Name
                main0
                Load
            )
            []
            []
        )
    )]
    []
)
