(Module
    [(ImportFrom
        lpython
        [(c32
        ())
        (c64
        ())]
        0
    )
    (FunctionDef
        test_complex
        ([]
        []
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                c
                Store
            )
            (Name
                c32
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                c1
                Store
            )
            (Name
                c32
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                c2
                Store
            )
            (Name
                c32
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                c3
                Store
            )
            (Name
                c64
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                b
                Store
            )
            (Name
                bool
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                c
                Store
            )]
            (Call
                (Name
                    c32
                    Load
                )
                [(Call
                    (Name
                        complex
                        Load
                    )
                    []
                    []
                )]
                []
            )
            ()
        )
        (Assign
            [(Name
                c
                Store
            )]
            (Call
                (Name
                    c32
                    Load
                )
                [(Call
                    (Name
                        complex
                        Load
                    )
                    [(ConstantFloat
                        3.400000
                        ()
                    )]
                    []
                )]
                []
            )
            ()
        )
        (Assign
            [(Name
                c
                Store
            )]
            (Call
                (Name
                    c32
                    Load
                )
                [(Call
                    (Name
                        complex
                        Load
                    )
                    [(ConstantFloat
                        5.000000
                        ()
                    )
                    (ConstantFloat
                        4.300000
                        ()
                    )]
                    []
                )]
                []
            )
            ()
        )
        (Assign
            [(Name
                c
                Store
            )]
            (Call
                (Name
                    c32
                    Load
                )
                [(Call
                    (Name
                        complex
                        Load
                    )
                    [(ConstantInt
                        1
                        ()
                    )]
                    []
                )]
                []
            )
            ()
        )
        (Assign
            [(Name
                c1
                Store
            )]
            (Call
                (Name
                    c32
                    Load
                )
                [(Call
                    (Name
                        complex
                        Load
                    )
                    [(ConstantInt
                        3
                        ()
                    )
                    (ConstantInt
                        4
                        ()
                    )]
                    []
                )]
                []
            )
            ()
        )
        (Assign
            [(Name
                c2
                Store
            )]
            (Call
                (Name
                    c32
                    Load
                )
                [(Call
                    (Name
                        complex
                        Load
                    )
                    [(ConstantInt
                        2
                        ()
                    )
                    (ConstantFloat
                        4.500000
                        ()
                    )]
                    []
                )]
                []
            )
            ()
        )
        (Assign
            [(Name
                c3
                Store
            )]
            (Call
                (Name
                    complex
                    Load
                )
                [(ConstantFloat
                    3.000000
                    ()
                )
                (ConstantFloat
                    4.000000
                    ()
                )]
                []
            )
            ()
        )
        (Assign
            [(Name
                b
                Store
            )]
            (Compare
                (Name
                    c1
                    Load
                )
                NotEq
                [(Name
                    c2
                    Load
                )]
            )
            ()
        )
        (Assign
            [(Name
                b
                Store
            )]
            (Compare
                (Call
                    (Name
                        c64
                        Load
                    )
                    [(Name
                        c1
                        Load
                    )]
                    []
                )
                Eq
                [(Name
                    c3
                    Load
                )]
            )
            ()
        )
        (Assign
            [(Name
                c
                Store
            )]
            (BinOp
                (Name
                    c1
                    Load
                )
                Add
                (Name
                    c2
                    Load
                )
            )
            ()
        )
        (Assign
            [(Name
                c
                Store
            )]
            (BinOp
                (Name
                    c2
                    Load
                )
                Sub
                (Name
                    c1
                    Load
                )
            )
            ()
        )
        (Assign
            [(Name
                c
                Store
            )]
            (BinOp
                (Name
                    c1
                    Load
                )
                Mult
                (Name
                    c2
                    Load
                )
            )
            ()
        )
        (Assign
            [(Name
                c
                Store
            )]
            (Call
                (Name
                    c32
                    Load
                )
                [(BinOp
                    (Call
                        (Name
                            complex
                            Load
                        )
                        [(ConstantInt
                            1
                            ()
                        )
                        (ConstantInt
                            2
                            ()
                        )]
                        []
                    )
                    Pow
                    (Call
                        (Name
                            complex
                            Load
                        )
                        [(ConstantFloat
                            3.345340
                            ()
                        )
                        (ConstantFloat
                            4.867868
                            ()
                        )]
                        []
                    )
                )]
                []
            )
            ()
        )
        (Assign
            [(Name
                c
                Store
            )]
            (Call
                (Name
                    c32
                    Load
                )
                [(BinOp
                    (Call
                        (Name
                            complex
                            Load
                        )
                        [(ConstantInt
                            1
                            ()
                        )
                        (ConstantInt
                            2
                            ()
                        )]
                        []
                    )
                    Mult
                    (Call
                        (Name
                            complex
                            Load
                        )
                        [(ConstantInt
                            3
                            ()
                        )
                        (ConstantInt
                            4
                            ()
                        )]
                        []
                    )
                )]
                []
            )
            ()
        )
        (Assign
            [(Name
                c
                Store
            )]
            (Call
                (Name
                    c32
                    Load
                )
                [(BinOp
                    (Call
                        (Name
                            complex
                            Load
                        )
                        [(ConstantInt
                            4
                            ()
                        )
                        (ConstantInt
                            5
                            ()
                        )]
                        []
                    )
                    Sub
                    (Call
                        (Name
                            complex
                            Load
                        )
                        [(ConstantInt
                            3
                            ()
                        )
                        (ConstantInt
                            4
                            ()
                        )]
                        []
                    )
                )]
                []
            )
            ()
        )]
        []
        ()
        ()
    )
    (FunctionDef
        test
        ([]
        []
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                x
                Store
            )
            (Name
                c64
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                y
                Store
            )
            (Name
                c64
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                z
                Store
            )
            (Name
                c32
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                x
                Store
            )]
            (BinOp
                (Call
                    (Name
                        c64
                        Load
                    )
                    [(ConstantInt
                        2
                        ()
                    )]
                    []
                )
                Add
                (ConstantComplex
                    0.000000
                    3.000000
                    ()
                )
            )
            ()
        )
        (Assign
            [(Name
                y
                Store
            )]
            (BinOp
                (Call
                    (Name
                        c64
                        Load
                    )
                    [(ConstantInt
                        5
                        ()
                    )]
                    []
                )
                Add
                (ConstantComplex
                    0.000000
                    5.000000
                    ()
                )
            )
            ()
        )
        (Assign
            [(Name
                z
                Store
            )]
            (Call
                (Name
                    c32
                    Load
                )
                [(BinOp
                    (Name
                        x
                        Load
                    )
                    Add
                    (Name
                        y
                        Load
                    )
                )]
                []
            )
            ()
        )
        (Assign
            [(Name
                z
                Store
            )]
            (Call
                (Name
                    c32
                    Load
                )
                [(BinOp
                    (Name
                        x
                        Load
                    )
                    Sub
                    (Name
                        y
                        Load
                    )
                )]
                []
            )
            ()
        )
        (Assign
            [(Name
                z
                Store
            )]
            (Call
                (Name
                    c32
                    Load
                )
                [(BinOp
                    (Call
                        (Name
                            c64
                            Load
                        )
                        [(ConstantInt
                            2
                            ()
                        )]
                        []
                    )
                    Mult
                    (Name
                        x
                        Load
                    )
                )]
                []
            )
            ()
        )]
        []
        ()
        ()
    )]
    []
)
