(Module
    [(ImportFrom
        sys
        [(exit
        ())]
        0
    )
    (FunctionDef
        test_for
        ([]
        []
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                i
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (For
            (Name
                i
                Store
            )
            (Call
                (Name
                    range
                    Load
                )
                [(ConstantInt
                    0
                    ()
                )
                (ConstantInt
                    10
                    ()
                )]
                []
            )
            [(If
                (Compare
                    (Name
                        i
                        Load
                    )
                    Eq
                    [(ConstantInt
                        0
                        ()
                    )]
                )
                [(Continue)]
                []
            )
            (If
                (Compare
                    (Name
                        i
                        Load
                    )
                    Gt
                    [(ConstantInt
                        5
                        ()
                    )]
                )
                [(Break)]
                []
            )
            (If
                (Compare
                    (Name
                        i
                        Load
                    )
                    Eq
                    [(ConstantInt
                        3
                        ()
                    )]
                )
                [(Expr
                    (Call
                        (Name
                            quit
                            Load
                        )
                        []
                        []
                    )
                )]
                []
            )]
            []
            ()
        )
        (Expr
            (Call
                (Name
                    exit
                    Load
                )
                [(ConstantInt
                    2
                    ()
                )]
                []
            )
        )]
        []
        ()
        ()
    )
    (Expr
        (Call
            (Name
                test_for
                Load
            )
            []
            []
        )
    )]
    []
)
