(Module
    [(FunctionDef
        main0
        ([]
        []
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                x
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                x2
                Store
            )
            (Name
                i64
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                y
                Store
            )
            (Name
                f32
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                y2
                Store
            )
            (Name
                f64
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                x
                Store
            )]
            (BinOp
                (BinOp
                    (ConstantInt
                        2
                        ()
                    )
                    Add
                    (ConstantInt
                        3
                        ()
                    )
                )
                Mult
                (ConstantInt
                    5
                    ()
                )
            )
            ()
        )
        (Expr
            (Call
                (Name
                    print
                    Load
                )
                [(Name
                    x
                    Load
                )]
                []
            )
        )]
        []
        ()
        ()
    )
    (Expr
        (Call
            (Name
                main0
                Load
            )
            []
            []
        )
    )]
    []
)
