(Module
    [(ImportFrom
        lpython
        [(f32
        ())
        (i32
        ())]
        0
    )
    (FunctionDef
        triad
        ([]
        [(a
        (Subscript
            (Name
                f32
                Load
            )
            (Slice
                ()
                ()
                ()
            )
            Load
        )
        ())
        (b
        (Subscript
            (Name
                f32
                Load
            )
            (Slice
                ()
                ()
                ()
            )
            Load
        )
        ())
        (scalar
        (Name
            f32
            Load
        )
        ())
        (c
        (Subscript
            (Name
                f32
                Load
            )
            (Slice
                ()
                ()
                ()
            )
            Load
        )
        ())]
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                N
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                i
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                N
                Store
            )]
            (Call
                (Name
                    size
                    Load
                )
                [(Name
                    a
                    Load
                )]
                []
            )
            ()
        )
        (For
            (Name
                i
                Store
            )
            (Call
                (Name
                    range
                    Load
                )
                [(Name
                    N
                    Load
                )]
                []
            )
            [(Assign
                [(Subscript
                    (Name
                        c
                        Load
                    )
                    (Name
                        i
                        Load
                    )
                    Store
                )]
                (BinOp
                    (Subscript
                        (Name
                            a
                            Load
                        )
                        (Name
                            i
                            Load
                        )
                        Load
                    )
                    Add
                    (BinOp
                        (Name
                            scalar
                            Load
                        )
                        Mult
                        (Subscript
                            (Name
                                b
                                Load
                            )
                            (Name
                                i
                                Load
                            )
                            Load
                        )
                    )
                )
                ()
            )]
            []
            "parallel"
        )]
        []
        ()
        ()
    )
    (FunctionDef
        main0
        ([]
        []
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                a
                Store
            )
            (Subscript
                (Name
                    f32
                    Load
                )
                (ConstantInt
                    10000
                    ()
                )
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                b
                Store
            )
            (Subscript
                (Name
                    f32
                    Load
                )
                (ConstantInt
                    10000
                    ()
                )
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                c
                Store
            )
            (Subscript
                (Name
                    f32
                    Load
                )
                (ConstantInt
                    10000
                    ()
                )
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                scalar
                Store
            )
            (Name
                f32
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                i
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                nsize
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                scalar
                Store
            )]
            (Call
                (Name
                    f32
                    Load
                )
                [(ConstantFloat
                    10.000000
                    ()
                )]
                []
            )
            ()
        )
        (Assign
            [(Name
                nsize
                Store
            )]
            (Call
                (Name
                    size
                    Load
                )
                [(Name
                    a
                    Load
                )]
                []
            )
            ()
        )
        (For
            (Name
                i
                Store
            )
            (Call
                (Name
                    range
                    Load
                )
                [(Name
                    nsize
                    Load
                )]
                []
            )
            [(Assign
                [(Subscript
                    (Name
                        a
                        Load
                    )
                    (Name
                        i
                        Load
                    )
                    Store
                )]
                (Call
                    (Name
                        f32
                        Load
                    )
                    [(ConstantFloat
                        5.000000
                        ()
                    )]
                    []
                )
                ()
            )
            (Assign
                [(Subscript
                    (Name
                        b
                        Load
                    )
                    (Name
                        i
                        Load
                    )
                    Store
                )]
                (Call
                    (Name
                        f32
                        Load
                    )
                    [(ConstantFloat
                        5.000000
                        ()
                    )]
                    []
                )
                ()
            )]
            []
            "parallel"
        )
        (Expr
            (Call
                (Name
                    triad
                    Load
                )
                [(Name
                    a
                    Load
                )
                (Name
                    b
                    Load
                )
                (Name
                    scalar
                    Load
                )
                (Name
                    c
                    Load
                )]
                []
            )
        )
        (Expr
            (Call
                (Name
                    print
                    Load
                )
                [(ConstantStr
                    "End Stream Triad"
                    ()
                )]
                []
            )
        )]
        []
        ()
        ()
    )
    (Expr
        (Call
            (Name
                main0
                Load
            )
            []
            []
        )
    )]
    []
)
