(Module
    [(FunctionDef
        test_assert
        ([]
        []
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                a
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                a
                Store
            )]
            (ConstantInt
                5
                ()
            )
            ()
        )
        (Assert
            (Compare
                (Name
                    a
                    Load
                )
                Eq
                [(ConstantInt
                    5
                    ()
                )]
            )
            (ConstantStr
                "a is not 5"
                ()
            )
        )
        (Assert
            (Compare
                (Name
                    a
                    Load
                )
                NotEq
                [(ConstantInt
                    10
                    ()
                )]
            )
            ()
        )]
        []
        ()
        ()
    )]
    []
)
