(Module
    [(Import
        [(numpy
        np)]
    )
    (ImportFrom
        typing
        [(Callable
        ())]
        0
    )
    (Assign
        [(Name
            array
            Store
        )]
        (Call
            (Attribute
                (Attribute
                    (Name
                        np
                        Load
                    )
                    random
                    Load
                )
                rand
                Load
            )
            [(ConstantInt
                2
                ()
            )
            (ConstantInt
                2
                ()
            )
            (ConstantInt
                2
                ()
            )
            (ConstantInt
                2
                ()
            )]
            []
        )
        ()
    )
    (Expr
        (Call
            (Name
                print
                Load
            )
            [(Subscript
                (Name
                    array
                    Load
                )
                (Tuple
                    [(ConstantEllipsis
                        ()
                    )
                    (ConstantInt
                        0
                        ()
                    )]
                    Load
                )
                Load
            )]
            []
        )
    )
    (Expr
        (Call
            (Name
                print
                Load
            )
            [(Subscript
                (Name
                    array
                    Load
                )
                (Tuple
                    [(Name
                        Ellipsis
                        Load
                    )
                    (ConstantInt
                        0
                        ()
                    )]
                    Load
                )
                Load
            )]
            []
        )
    )
    (FunctionDef
        inject
        ([]
        [(get_next_item
        (Subscript
            (Name
                Callable
                Load
            )
            (Tuple
                [(ConstantEllipsis
                    ()
                )
                (Name
                    str
                    Load
                )]
                Load
            )
            Load
        )
        ())]
        []
        []
        []
        []
        [])
        [(Expr
            (ConstantEllipsis
                ()
            )
        )]
        []
        (ConstantNone
            ()
        )
        ()
    )
    (FunctionDef
        foo
        ([]
        [(x
        (ConstantEllipsis
            ()
        )
        ())]
        []
        []
        []
        []
        [])
        [(Expr
            (ConstantEllipsis
                ()
            )
        )]
        []
        (ConstantNone
            ()
        )
        ()
    )
    (ClassDef
        flow
        []
        []
        [(FunctionDef
            __understand__
            ([]
            [(self
            ()
            ())
            (name
            (Name
                str
                Load
            )
            ())
            (value
            (ConstantEllipsis
                ()
            )
            ())]
            []
            []
            []
            []
            [])
            [(Expr
                (ConstantEllipsis
                    ()
                )
            )]
            []
            (ConstantNone
                ()
            )
            ()
        )]
        []
    )
    (FunctionDef
        foo
        ([]
        [(x
        ()
        ())]
        []
        []
        []
        []
        [(ConstantEllipsis
            ()
        )])
        [(Return
            (Name
                x
                Load
            )
        )]
        []
        ()
        ()
    )
    (FunctionDef
        test
        ([]
        []
        []
        []
        []
        []
        [])
        [(Expr
            (ConstantEllipsis
                ()
            )
        )]
        []
        ()
        ()
    )
    (ClassDef
        Todo
        []
        []
        [(Expr
            (ConstantEllipsis
                ()
            )
        )]
        []
    )
    (Assign
        [(Name
            x
            Store
        )]
        (List
            [(ConstantInt
                1
                ()
            )
            (List
                [(ConstantInt
                    2
                    ()
                )
                (List
                    [(ConstantEllipsis
                        ()
                    )]
                    Load
                )
                (ConstantInt
                    3
                    ()
                )]
                Load
            )]
            Load
        )
        ()
    )
    (Assign
        [(Name
            l
            Store
        )]
        (List
            [(ConstantEllipsis
                ()
            )
            (ConstantInt
                1
                ()
            )
            (ConstantInt
                2
                ()
            )
            (ConstantInt
                3
                ()
            )]
            Load
        )
        ()
    )
    (If
        (Compare
            (Name
                x
                Load
            )
            Is
            [(ConstantEllipsis
                ()
            )]
        )
        [(Pass)]
        []
    )
    (FunctionDef
        partial
        ([]
        [(func
        (Subscript
            (Name
                Callable
                Load
            )
            (Tuple
                [(ConstantEllipsis
                    ()
                )
                (Name
                    str
                    Load
                )]
                Load
            )
            Load
        )
        ())]
        [(args
        ()
        ())]
        []
        []
        []
        [])
        [(Pass)]
        []
        (Subscript
            (Name
                Callable
                Load
            )
            (Tuple
                [(ConstantEllipsis
                    ()
                )
                (Name
                    str
                    Load
                )]
                Load
            )
            Load
        )
        ()
    )
    (ClassDef
        xyz
        []
        []
        [(AnnAssign
            (Name
                abc
                Store
            )
            (Name
                str
                Load
            )
            (ConstantEllipsis
                ()
            )
            1
        )
        (FunctionDef
            __init__
            ([]
            [(self
            ()
            ())
            (name
            (Name
                str
                Load
            )
            ())]
            []
            []
            []
            []
            [(ConstantEllipsis
                ()
            )])
            [(Expr
                (ConstantEllipsis
                    ()
                )
            )]
            []
            (ConstantNone
                ()
            )
            ()
        )]
        []
    )]
    []
)
