(Module
    [(ImportFrom
        lpython
        [(i32
        ())
        (f32
        ())]
        0
    )
    (FunctionDef
        test_Tuple
        ([]
        []
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                a1
                Store
            )
            (Subscript
                (Name
                    tuple
                    Load
                )
                (Tuple
                    [(Name
                        i32
                        Load
                    )
                    (Name
                        i32
                        Load
                    )
                    (Name
                        i32
                        Load
                    )]
                    Load
                )
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                a1
                Store
            )]
            (Tuple
                [(ConstantInt
                    1
                    ()
                )
                (ConstantInt
                    2
                    ()
                )
                (ConstantInt
                    3
                    ()
                )]
                Load
            )
            ()
        )
        (Assign
            [(Name
                a1
                Store
            )]
            (Tuple
                [(UnaryOp
                    USub
                    (ConstantInt
                        3
                        ()
                    )
                )
                (UnaryOp
                    USub
                    (ConstantInt
                        2
                        ()
                    )
                )
                (UnaryOp
                    USub
                    (ConstantInt
                        1
                        ()
                    )
                )]
                Load
            )
            ()
        )
        (AnnAssign
            (Name
                a2
                Store
            )
            (Subscript
                (Name
                    tuple
                    Load
                )
                (Tuple
                    [(Name
                        str
                        Load
                    )
                    (Name
                        str
                        Load
                    )
                    (Name
                        str
                        Load
                    )]
                    Load
                )
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                a2
                Store
            )]
            (Tuple
                [(ConstantStr
                    "a"
                    ()
                )
                (ConstantStr
                    "b"
                    ()
                )
                (ConstantStr
                    "c"
                    ()
                )]
                Load
            )
            ()
        )
        (AnnAssign
            (Name
                a3
                Store
            )
            (Subscript
                (Name
                    tuple
                    Load
                )
                (Tuple
                    [(Name
                        i32
                        Load
                    )
                    (Name
                        i32
                        Load
                    )
                    (Name
                        f32
                        Load
                    )
                    (Name
                        str
                        Load
                    )]
                    Load
                )
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                float_mem
                Store
            )
            (Name
                f32
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                float_mem
                Store
            )]
            (Call
                (Name
                    f32
                    Load
                )
                [(ConstantFloat
                    0.450000
                    ()
                )]
                []
            )
            ()
        )
        (Assign
            [(Name
                a3
                Store
            )]
            (Tuple
                [(UnaryOp
                    USub
                    (ConstantInt
                        2
                        ()
                    )
                )
                (UnaryOp
                    USub
                    (ConstantInt
                        1
                        ()
                    )
                )
                (Name
                    float_mem
                    Load
                )
                (ConstantStr
                    "d"
                    ()
                )]
                Load
            )
            ()
        )
        (AnnAssign
            (Name
                a4
                Store
            )
            (Subscript
                (Name
                    tuple
                    Load
                )
                (Tuple
                    [(Subscript
                        (Name
                            tuple
                            Load
                        )
                        (Tuple
                            [(Name
                                i32
                                Load
                            )
                            (Name
                                i32
                                Load
                            )
                            (Name
                                i32
                                Load
                            )]
                            Load
                        )
                        Load
                    )
                    (Subscript
                        (Name
                            tuple
                            Load
                        )
                        (Tuple
                            [(Name
                                i32
                                Load
                            )
                            (Name
                                i32
                                Load
                            )
                            (Name
                                i32
                                Load
                            )]
                            Load
                        )
                        Load
                    )]
                    Load
                )
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                a4
                Store
            )]
            (Tuple
                [(Tuple
                    [(ConstantInt
                        1
                        ()
                    )
                    (ConstantInt
                        2
                        ()
                    )
                    (ConstantInt
                        3
                        ()
                    )]
                    Load
                )
                (Tuple
                    [(ConstantInt
                        4
                        ()
                    )
                    (ConstantInt
                        5
                        ()
                    )
                    (ConstantInt
                        6
                        ()
                    )]
                    Load
                )]
                Load
            )
            ()
        )
        (AnnAssign
            (Name
                a5
                Store
            )
            (Subscript
                (Name
                    tuple
                    Load
                )
                (Tuple
                    [(Subscript
                        (Name
                            tuple
                            Load
                        )
                        (Tuple
                            [(Name
                                str
                                Load
                            )
                            (Name
                                str
                                Load
                            )
                            (Name
                                f32
                                Load
                            )]
                            Load
                        )
                        Load
                    )
                    (Subscript
                        (Name
                            tuple
                            Load
                        )
                        (Tuple
                            [(Name
                                str
                                Load
                            )
                            (Name
                                i32
                                Load
                            )
                            (Name
                                f32
                                Load
                            )]
                            Load
                        )
                        Load
                    )]
                    Load
                )
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                float_mem1
                Store
            )
            (Name
                f32
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                float_mem2
                Store
            )
            (Name
                f32
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                float_mem1
                Store
            )]
            (Call
                (Name
                    f32
                    Load
                )
                [(ConstantFloat
                    3.400000
                    ()
                )]
                []
            )
            ()
        )
        (Assign
            [(Name
                float_mem2
                Store
            )]
            (Call
                (Name
                    f32
                    Load
                )
                [(ConstantFloat
                    5.600000
                    ()
                )]
                []
            )
            ()
        )
        (Assign
            [(Name
                a5
                Store
            )]
            (Tuple
                [(Tuple
                    [(ConstantStr
                        "a"
                        ()
                    )
                    (ConstantStr
                        "b"
                        ()
                    )
                    (Name
                        float_mem1
                        Load
                    )]
                    Load
                )
                (Tuple
                    [(ConstantStr
                        "c"
                        ()
                    )
                    (ConstantInt
                        3
                        ()
                    )
                    (Name
                        float_mem2
                        Load
                    )]
                    Load
                )]
                Load
            )
            ()
        )
        (AnnAssign
            (Name
                b0
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                b1
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                b0
                Store
            )]
            (Subscript
                (Name
                    a1
                    Load
                )
                (ConstantInt
                    0
                    ()
                )
                Load
            )
            ()
        )
        (Assign
            [(Tuple
                [(Name
                    b0
                    Store
                )
                (Name
                    b1
                    Store
                )]
                Store
            )]
            (Tuple
                [(Subscript
                    (Name
                        a1
                        Load
                    )
                    (ConstantInt
                        2
                        ()
                    )
                    Load
                )
                (Subscript
                    (Name
                        a1
                        Load
                    )
                    (ConstantInt
                        1
                        ()
                    )
                    Load
                )]
                Load
            )
            ()
        )
        (AnnAssign
            (Name
                a11
                Store
            )
            (Subscript
                (Name
                    tuple
                    Load
                )
                (Tuple
                    [(Name
                        i32
                        Load
                    )
                    (Name
                        i32
                        Load
                    )]
                    Load
                )
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                b11
                Store
            )
            (Subscript
                (Name
                    tuple
                    Load
                )
                (Tuple
                    [(Name
                        i32
                        Load
                    )
                    (Name
                        i32
                        Load
                    )]
                    Load
                )
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                a11
                Store
            )]
            (Tuple
                [(ConstantInt
                    1
                    ()
                )
                (ConstantInt
                    2
                    ()
                )]
                Load
            )
            ()
        )
        (Assign
            [(Name
                b11
                Store
            )]
            (Tuple
                [(ConstantInt
                    1
                    ()
                )
                (ConstantInt
                    2
                    ()
                )]
                Load
            )
            ()
        )
        (Assert
            (Compare
                (Name
                    a11
                    Load
                )
                Eq
                [(Name
                    b11
                    Load
                )]
            )
            ()
        )]
        []
        ()
        ()
    )]
    []
)
