(Module
    [(FunctionDef
        test_augassign
        ([]
        []
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                r
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (AnnAssign
            (Name
                s
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                r
                Store
            )]
            (ConstantInt
                0
                ()
            )
            ()
        )
        (AugAssign
            (Name
                r
                Store
            )
            Add
            (ConstantInt
                4
                ()
            )
        )
        (Assign
            [(Name
                s
                Store
            )]
            (ConstantInt
                5
                ()
            )
            ()
        )
        (AugAssign
            (Name
                r
                Store
            )
            Mult
            (Name
                s
                Load
            )
        )
        (AugAssign
            (Name
                r
                Store
            )
            Sub
            (ConstantInt
                2
                ()
            )
        )
        (Assign
            [(Name
                s
                Store
            )]
            (ConstantInt
                10
                ()
            )
            ()
        )
        (AugAssign
            (Name
                r
                Store
            )
            Div
            (Name
                s
                Load
            )
        )
        (AnnAssign
            (Name
                a
                Store
            )
            (Name
                str
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                a
                Store
            )]
            (ConstantStr
                ""
                ()
            )
            ()
        )
        (AugAssign
            (Name
                a
                Store
            )
            Add
            (ConstantStr
                "test"
                ()
            )
        )]
        []
        ()
        ()
    )]
    []
)
