(Module
    [(FunctionDef
        test_frompyfunc_name
        ([]
        [(self
        ()
        ())]
        []
        []
        []
        []
        [])
        [(FunctionDef
            cassé
            ([]
            [(x
            ()
            ())]
            []
            []
            []
            []
            [])
            [(Return
                (Name
                    x
                    Load
                )
            )]
            []
            ()
            ()
        )]
        []
        ()
        ()
    )
    (Assign
        [(Name
            ℙƴtℌøἤ
            Store
        )]
        (ConstantInt
            1
            ()
        )
        ()
    )
    (Expr
        (Call
            (Name
                print
                Load
            )
            [(Name
                ℙƴtℌøἤ
                Load
            )]
            []
        )
    )
    (If
        (Compare
            (Name
                诶
                Load
            )
            NotEq
            [(ConstantInt
                2
                ()
            )]
        )
        [(Pass)]
        []
    )
    (FunctionDef
        क१
        ([]
        []
        []
        []
        []
        []
        [])
        [(Expr
            (ConstantEllipsis
                ()
            )
        )]
        []
        ()
        ()
    )]
    []
)
