(Module
    [(ImportFrom
        lpython
        [(i32
        ())]
        0
    )
    (AnnAssign
        (Name
            i
            Store
        )
        (Name
            i32
            Load
        )
        (ConstantInt
            10
            ()
        )
        1
    )
    (While
        (Compare
            (Name
                i
                Load
            )
            Lt
            [(ConstantInt
                3
                ()
            )]
        )
        [(Pass)]
        []
    )
    (While
        (Compare
            (Name
                i
                Load
            )
            Lt
            [(ConstantInt
                6
                ()
            )]
        )
        [(Pass)]
        [(Pass)]
    )
    (While
        (Compare
            (Name
                i
                Load
            )
            Lt
            [(ConstantInt
                3
                ()
            )]
        )
        [(Pass)]
        []
    )
    (While
        (Compare
            (Name
                i
                Load
            )
            Lt
            [(ConstantInt
                6
                ()
            )]
        )
        [(Pass)]
        [(Pass)]
    )]
    []
)
