(Module
    [(Expr
        (JoinedStr
            [(ConstantStr
                "Hello, "
                ()
            )
            (FormattedValue
                (Name
                    first_name
                    Load
                )
                -1
                ()
            )
            (ConstantStr
                " "
                ()
            )
            (FormattedValue
                (Name
                    last_name
                    Load
                )
                -1
                ()
            )
            (ConstantStr
                ". You are "
                ()
            )
            (FormattedValue
                (Name
                    age
                    Load
                )
                -1
                ()
            )
            (ConstantStr
                " years old."
                ()
            )]
        )
    )
    (Expr
        (Call
            (Name
                print
                Load
            )
            [(JoinedStr
                [(FormattedValue
                    (Name
                        __file__
                        Load
                    )
                    -1
                    ()
                )
                (ConstantStr
                    " executed in "
                    ()
                )
                (FormattedValue
                    (Name
                        elapsed
                        Load
                    )
                    -1
                    ()
                )
                (ConstantStr
                    " seconds."
                    ()
                )]
            )]
            []
        )
    )
    (Expr
        (ConstantStr
            "\nsometext\nanotherline\n"
            ()
        )
    )
    (Expr
        (ConstantBytes
            "b'Some text goes here.'"
            ()
        )
    )
    (Expr
        (ConstantBytes
            "b'\nMultiple texts goes here.\n'"
            ()
        )
    )
    (Expr
        (ConstantStr
            "\nText\n"
            ()
        )
    )
    (Expr
        (ConstantStr
            "Text"
            ()
        )
    )
    (Expr
        (ConstantStr
            "a\\tb\\nA\\tB"
            ()
        )
    )
    (Expr
        (ConstantStr
            "1,2,3 # comment"
            "u"
        )
    )
    (Expr
        (ConstantStr
            "Text"
            "u"
        )
    )
    (Expr
        (ConstantStr
            "Text"
            ()
        )
    )
    (Expr
        (JoinedStr
            [(ConstantStr
                "Text "
                ()
            )
            (FormattedValue
                (Name
                    id
                    Load
                )
                -1
                ()
            )]
        )
    )
    (Expr
        (JoinedStr
            [(ConstantStr
                "Text "
                ()
            )
            (FormattedValue
                (Name
                    id
                    Load
                )
                -1
                ()
            )]
        )
    )
    (Expr
        (JoinedStr
            [(ConstantStr
                "Text "
                ()
            )
            (FormattedValue
                (Name
                    id
                    Load
                )
                -1
                ()
            )]
        )
    )
    (Expr
        (JoinedStr
            [(ConstantStr
                "Text "
                ()
            )
            (FormattedValue
                (Name
                    id
                    Load
                )
                -1
                ()
            )]
        )
    )
    (Expr
        (JoinedStr
            [(ConstantStr
                "Text "
                ()
            )
            (FormattedValue
                (Name
                    id
                    Load
                )
                -1
                ()
            )]
        )
    )
    (Expr
        (JoinedStr
            [(ConstantStr
                "\nText "
                ()
            )
            (FormattedValue
                (Name
                    id
                    Load
                )
                -1
                ()
            )
            (ConstantStr
                "\n"
                ()
            )]
        )
    )
    (Expr
        (JoinedStr
            [(ConstantStr
                "Text "
                ()
            )
            (FormattedValue
                (Name
                    id
                    Load
                )
                -1
                ()
            )]
        )
    )
    (Expr
        (JoinedStr
            [(ConstantStr
                "Text "
                ()
            )
            (FormattedValue
                (Name
                    id
                    Load
                )
                -1
                ()
            )]
        )
    )
    (Expr
        (ConstantBytes
            "b'Text'"
            ()
        )
    )
    (Expr
        (ConstantBytes
            "b'\nText\n'"
            ()
        )
    )
    (Expr
        (ConstantBytes
            "b'Text'"
            ()
        )
    )
    (Expr
        (ConstantBytes
            "b'Text'"
            ()
        )
    )
    (Expr
        (ConstantBytes
            "b'Text'"
            ()
        )
    )
    (Expr
        (ConstantBytes
            "b'\nText\n'"
            ()
        )
    )
    (Expr
        (ConstantBytes
            "b'Text'"
            ()
        )
    )
    (Expr
        (ConstantBytes
            "b'Text'"
            ()
        )
    )
    (Expr
        (JoinedStr
            [(ConstantStr
                "\\N"
                ()
            )
            (FormattedValue
                (Name
                    AMPERSAND
                    Load
                )
                -1
                ()
            )]
        )
    )
    (Expr
        (JoinedStr
            [(ConstantStr
                "Text"
                ()
            )
            (FormattedValue
                (Name
                    a
                    Load
                )
                -1
                ()
            )
            (ConstantStr
                ", "
                ()
            )
            (FormattedValue
                (Name
                    b
                    Load
                )
                -1
                ()
            )
            (ConstantStr
                "Text "
                ()
            )
            (FormattedValue
                (Name
                    a
                    Load
                )
                -1
                ()
            )]
        )
    )
    (Expr
        (JoinedStr
            [(ConstantStr
                "Text"
                ()
            )
            (FormattedValue
                (Name
                    a
                    Load
                )
                -1
                ()
            )
            (ConstantStr
                ", "
                ()
            )
            (FormattedValue
                (Name
                    b
                    Load
                )
                -1
                ()
            )
            (ConstantStr
                "Text"
                ()
            )]
        )
    )
    (Expr
        (JoinedStr
            [(ConstantStr
                "Text"
                ()
            )
            (FormattedValue
                (Name
                    b
                    Load
                )
                -1
                ()
            )
            (ConstantStr
                ", Text"
                ()
            )]
        )
    )
    (Expr
        (JoinedStr
            [(ConstantStr
                "Text "
                ()
            )
            (FormattedValue
                (Name
                    a
                    Load
                )
                -1
                ()
            )
            (ConstantStr
                "Text"
                ()
            )]
        )
    )
    (Expr
        (ConstantStr
            "TextText"
            ()
        )
    )
    (Expr
        (ConstantStr
            "TextText"
            ()
        )
    )
    (Expr
        (JoinedStr
            [(ConstantStr
                "Text"
                ()
            )
            (FormattedValue
                (Name
                    a
                    Load
                )
                -1
                ()
            )
            (ConstantStr
                " Text"
                ()
            )]
        )
    )
    (Expr
        (ConstantBytes
            "b'TextText'"
            ()
        )
    )
    (Expr
        (ConstantStr
            "\\n"
            ()
        )
    )
    (Expr
        (ConstantStr
            "\nText\n123\\n\\t\n"
            ()
        )
    )
    (Expr
        (ConstantBytes
            "b'\\n'"
            ()
        )
    )
    (Expr
        (JoinedStr
            [(ConstantStr
                "\\n"
                ()
            )]
        )
    )
    (Expr
        (ConstantBytes
            "b'\n'"
            ()
        )
    )
    (Expr
        (ConstantBytes
            "b'\n\n\\n'"
            ()
        )
    )]
    []
)
