(Module
    [(FunctionDef
        func
        ([]
        []
        []
        []
        []
        []
        [])
        [(AnnAssign
            (Name
                x
                Store
            )
            (Subscript
                (Name
                    list
                    Load
                )
                (Name
                    i32
                    Load
                )
                Load
            )
            ()
            1
        )
        (Assign
            [(Name
                x
                Store
            )]
            (List
                [(ConstantInt
                    1
                    ()
                )
                (ConstantInt
                    2
                    ()
                )
                (ConstantInt
                    3
                    ()
                )]
                Load
            )
            ()
        )
        (AnnAssign
            (Name
                i
                Store
            )
            (Name
                i32
                Load
            )
            ()
            1
        )
        (For
            (Name
                i
                Store
            )
            (Name
                x
                Load
            )
            [(Expr
                (Yield
                    (Name
                        i
                        Load
                    )
                )
            )]
            []
            ()
        )
        (For
            (Name
                i
                Store
            )
            (Name
                x
                Load
            )
            [(Expr
                (Yield
                    (Name
                        i
                        Load
                    )
                )
            )]
            []
            ()
        )
        (For
            (Name
                i
                Store
            )
            (Name
                x
                Load
            )
            [(Expr
                (Yield
                    (Tuple
                        []
                        Load
                    )
                )
            )]
            []
            ()
        )
        (For
            (Name
                _
                Store
            )
            (Name
                x
                Load
            )
            [(Expr
                (Yield
                    ()
                )
            )]
            []
            ()
        )
        (Expr
            (Yield
                (Tuple
                    [(Name
                        x
                        Load
                    )
                    (Name
                        y
                        Load
                    )]
                    Load
                )
            )
        )
        (Expr
            (Yield
                (Tuple
                    [(Name
                        x
                        Load
                    )
                    (Name
                        y
                        Load
                    )]
                    Load
                )
            )
        )]
        []
        ()
        ()
    )
    (FunctionDef
        iterable1
        ([]
        []
        []
        []
        []
        []
        [])
        [(Expr
            (Yield
                (ConstantInt
                    1
                    ()
                )
            )
        )
        (Expr
            (Yield
                (ConstantInt
                    2
                    ()
                )
            )
        )]
        []
        ()
        ()
    )
    (FunctionDef
        iterable2
        ([]
        []
        []
        []
        []
        []
        [])
        [(Expr
            (YieldFrom
                (Call
                    (Name
                        iterable1
                        Load
                    )
                    []
                    []
                )
            )
        )
        (Expr
            (Yield
                (ConstantInt
                    3
                    ()
                )
            )
        )]
        []
        ()
        ()
    )
    (Assert
        (Compare
            (Call
                (Name
                    list
                    Load
                )
                [(Call
                    (Name
                        iterable2
                        Load
                    )
                    []
                    []
                )]
                []
            )
            Eq
            [(List
                [(ConstantInt
                    1
                    ()
                )
                (ConstantInt
                    2
                    ()
                )
                (ConstantInt
                    3
                    ()
                )]
                Load
            )]
        )
        ()
    )
    (FunctionDef
        test_02
        ([]
        []
        []
        []
        []
        []
        [])
        [(Assign
            [(Name
                x
                Store
            )]
            (Yield
                (ConstantInt
                    123
                    ()
                )
            )
            ()
        )
        (Assign
            [(Name
                generator
                Store
            )]
            (Call
                (Name
                    type
                    Load
                )
                [(Call
                    (Lambda
                        ([]
                        []
                        []
                        []
                        []
                        []
                        [])
                        (Yield
                            ()
                        )
                    )
                    []
                    []
                )]
                []
            )
            ()
        )
        (Return
            (YieldFrom
                (Call
                    (Attribute
                        (Name
                            awaitable
                            Load
                        )
                        __await__
                        Load
                    )
                    []
                    []
                )
            )
        )]
        []
        ()
        ()
    )]
    []
)
