(Module
    [(Expr
        (Subscript
            (ConstantStr
                "LPython"
                ()
            )
            (Slice
                (ConstantInt
                    1
                    ()
                )
                (ConstantInt
                    2
                    ()
                )
                ()
            )
            Load
        )
    )
    (Expr
        (Subscript
            (ConstantStr
                "LPython"
                ()
            )
            (Slice
                (ConstantInt
                    1
                    ()
                )
                ()
                ()
            )
            Load
        )
    )
    (Expr
        (Subscript
            (ConstantStr
                "LPython"
                ()
            )
            (Slice
                ()
                (ConstantInt
                    2
                    ()
                )
                ()
            )
            Load
        )
    )
    (Expr
        (Subscript
            (ConstantStr
                "LPython"
                ()
            )
            (Slice
                ()
                ()
                ()
            )
            Load
        )
    )
    (Expr
        (Subscript
            (ConstantStr
                "LPython"
                ()
            )
            (Slice
                (ConstantInt
                    1
                    ()
                )
                (ConstantInt
                    2
                    ()
                )
                (ConstantInt
                    3
                    ()
                )
            )
            Load
        )
    )
    (Expr
        (Subscript
            (ConstantStr
                "LPython"
                ()
            )
            (Slice
                (ConstantInt
                    1
                    ()
                )
                (ConstantInt
                    2
                    ()
                )
                ()
            )
            Load
        )
    )
    (Expr
        (Subscript
            (ConstantStr
                "LPython"
                ()
            )
            (Slice
                (ConstantInt
                    1
                    ()
                )
                ()
                (ConstantInt
                    3
                    ()
                )
            )
            Load
        )
    )
    (Expr
        (Subscript
            (ConstantStr
                "LPython"
                ()
            )
            (Slice
                ()
                (ConstantInt
                    2
                    ()
                )
                (ConstantInt
                    3
                    ()
                )
            )
            Load
        )
    )
    (Expr
        (Subscript
            (ConstantStr
                "LPython"
                ()
            )
            (Slice
                ()
                ()
                (ConstantInt
                    3
                    ()
                )
            )
            Load
        )
    )
    (Expr
        (Subscript
            (ConstantStr
                "LPython"
                ()
            )
            (Slice
                ()
                (ConstantInt
                    2
                    ()
                )
                ()
            )
            Load
        )
    )
    (Expr
        (Subscript
            (ConstantStr
                "LPython"
                ()
            )
            (Slice
                (ConstantInt
                    1
                    ()
                )
                ()
                ()
            )
            Load
        )
    )
    (Expr
        (Subscript
            (ConstantStr
                "LPython"
                ()
            )
            (Slice
                ()
                ()
                ()
            )
            Load
        )
    )
    (Assign
        [(Name
            List
            Store
        )]
        (List
            [(ConstantStr
                "a"
                ()
            )
            (ConstantStr
                "b"
                ()
            )
            (ConstantStr
                "c"
                ()
            )
            (ConstantStr
                "d"
                ()
            )]
            Load
        )
        ()
    )
    (Assign
        [(Name
            List
            Store
        )]
        (List
            [(ConstantStr
                "a"
                ()
            )
            (ConstantStr
                "b"
                ()
            )
            (ConstantStr
                "c"
                ()
            )
            (ConstantStr
                "d"
                ()
            )]
            Load
        )
        ()
    )
    (Expr
        (Subscript
            (Name
                List
                Load
            )
            (Slice
                ()
                ()
                (UnaryOp
                    USub
                    (ConstantInt
                        2
                        ()
                    )
                )
            )
            Load
        )
    )]
    []
)
