name: lp
channels:
  - conda-forge
dependencies:
  - git
  - pip
  - make
  - re2c
  - toml
  - zlib
  - cmake
  - ninja
  - numpy
  - xonsh
  - flake8
  - setuptools
  - python=3.10.2
  - m2-bison=3.0.4
  - llvmdev=11.1.0
  - zstd-static=1.5.5
