#!/bin/bash

set -e
set -x

if [[ $1 == "" ]]; then
    echo "Test local lfort"
    PATH="$(pwd):$PATH"
    export FC=lfort
    bdir=build-lfort-local
elif [[ $1 == "lfort" ]]; then
    echo "Test installed lfort"
    export FC=lfort
    bdir=build-lfort
elif [[ $1 == "gfortran" ]]; then
    echo "Test installed gfortran"
    export FC=gfortran
    bdir=build-gfortran
else
    echo "Invalid option"
    exit 1
fi

rm -rf $bdir
mkdir $bdir
cd $bdir
cmake ../integration_tests
make
ctest
