#!/bin/bash

set -e
set -x

f=`pwd`/examples/expr2.f90
ASM_PATTERN="movq\|movl\|retq"
FC=lfort
#FC=gfortran

cd $(mktemp -d)
$FC $f
[ -f "a.out" ]
[ -x "a.out" ]
./a.out

cd $(mktemp -d)
$FC -c $f
[ -f "expr2.o" ]
[ ! -x "expr2.o" ]
$FC -o expr2 expr2.o
[ -f "expr2" ]
[ -x "expr2" ]
./expr2

cd $(mktemp -d)
$FC -o xx1 -c $f
[ -f "xx1" ]
[ ! -x "xx1" ]
$FC -o expr2 xx1
[ -f "expr2" ]
[ -x "expr2" ]
./expr2

cd $(mktemp -d)
$FC -o xx1 $f
[ -f "xx1" ]
[ -x "xx1" ]
./xx1

cd $(mktemp -d)
$FC -S $f
[ -f "expr2.s" ]
grep $ASM_PATTERN expr2.s

cd $(mktemp -d)
$FC -S -c $f
[ -f "expr2.s" ]
grep $ASM_PATTERN expr2.s

cd $(mktemp -d)
$FC -S -o xx1 $f
[ -f "xx1" ]
grep $ASM_PATTERN xx1

cd $(mktemp -d)
$FC -S -o xx1 -c $f
[ -f "xx1" ]
grep $ASM_PATTERN xx1

# LFortran specific options
cd $(mktemp -d)
$FC --show-ast $f
[ ! -f "expr2.o" ]

cd $(mktemp -d)
$FC -emit-llvm $f
[ -f "expr2.ll" ]

echo "All tests succeeded"
