#!/bin/bash

set -e
set -x

bdir=build-gfortran
rm -rf $bdir
mkdir $bdir
cd $bdir
FC=gfortran cmake ..
make
ctest
cd ..

bdir=build-lfort
rm -rf $bdir
mkdir $bdir
cd $bdir
FC=lfort cmake ..
make
ctest
cd ..
