"""
LFortran type kind numbers

The contents of this module was generated by the following code,
compiled with GFortran 9.1.0:

```fortran
program print_kinds
use iso_fortran_env
implicit none
integer :: i
print "('int8 = ', i0)", int8
print "('int16 = ', i0)", int16
print "('int32 = ', i0)", int32
print "('int64 = ', i0)", int64
print *
print "('real32 = ', i0)", real32
print "('real64 = ', i0)", real64
print "('real128 = ', i0)", real128
print *
do i = 1, size(logical_kinds)
    print "('logical', i0, ' = ', i0)", logical_kinds(i)*8, logical_kinds(i)
end do
print *
do i = 1, size(character_kinds)
    print "('char', i0, ' = ', i0)", character_kinds(i)*8, character_kinds(i)
end do
end
```

"""

int8 = 1
int16 = 2
int32 = 4
int64 = 8

real32 = 4
real64 = 8
real128 = 16

logical8 = 1
logical16 = 2
logical32 = 4
logical64 = 8
logical128 = 16

char8 = 1
char32 = 4
