"""
LFortran type kind numbers

The contents of this module was generated by the following code,
compiled with GFortran 9.1.0:

```fortran
program print_kinds
use iso_fortran_env
implicit none
integer :: i
do i = 1, size(integer_kinds)
    print "('int', i0, ' = ', i0)", integer_kinds(i)*8, integer_kinds(i)
end do
print *
do i = 1, size(real_kinds)
    print "('real', i0, ' = ', i0)", real_kinds(i)*8, real_kinds(i)
end do
print *
do i = 1, size(logical_kinds)
    print "('logical', i0, ' = ', i0)", logical_kinds(i)*8, logical_kinds(i)
end do
print *
do i = 1, size(character_kinds)
    print "('char', i0, ' = ', i0)", character_kinds(i)*8, character_kinds(i)
end do
end
```

"""

int8 = 1
int16 = 2
int32 = 4
int64 = 8
int128 = 16

real32 = 4
real64 = 8
real80 = 10
real128 = 16

logical8 = 1
logical16 = 2
logical32 = 4
logical64 = 8
logical128 = 16

char8 = 1
char32 = 4
