name: lp
channels:
  - conda-forge
  - defaults
dependencies:
  - git
  - pip
  - make
  - re2c
  - toml
  - zlib
  - cmake
  - numpy
  - flake8
  - setuptools
  - bison=3.4
  - python=3.10.2
  - zstd-static=1.5
  - symengine=0.12.0
  - sympy=1.11.1
