"LPython"[1:2]
"LPython"[1:]
"LPython"[:2]
"LPython"[:]
"LPython"[1:2:3]
"LPython"[1:2:]
"LPython"[1::3]
"LPython"[:2:3]
"LPython"[::3]
"LPython"[:2:]
"LPython"[1::]
"LPython"[::]
List = ['a', 'b', 'c', 'd']
List = ['a', 'b', 'c', 'd',]
List[::-2]
