name: Windows tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


env:
  # Increase this value to reset cache if ci/environment.yml has not changed
  CACHE_NUMBER: 0


jobs:
  Build:

    name: LPython Windows CI (3.10)
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: test
          use-only-tar-bz2: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: C:\Miniconda\envs\test
          key: windows-64-conda-${{ hashFiles('ci/environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: conda env update -n test -f ci/environment.yml

      - name: Install Windows Conda Packages
        run: conda install -n test -c conda-forge m2-bison=3.0.4 ninja xeus=1.0.1

      - name: Conda info
        shell: bash -l {0}
        run: |
            conda info
            conda list

      - name: Build and test
        shell: cmd
        run: |
            set CONDA_INSTALL_LOCN=C:\\Miniconda
            call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
            call conda activate test
            set LFORTRAN_CMAKE_GENERATOR=Ninja
            set WIN=1
            set MACOS=0
            call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            xonsh ci\build.xsh
